#!/usr/bin/env ruby
# frozen_string_literal: true

# See also https://github.com/bhserna/specific_preloading_with_scoped_associations

require 'bundler/inline'

# From https://greg.molnar.io/blog/a-single-file-rails-application/
# Necessary for single file Rails application, not sure how I want
# to handle this yet.
gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails'
  gem 'sqlite3'
  gem 'colorize'
  gem 'pg_query'
  gem 'cli-ui' # https://github.com/Shopify/cli-ui
end

require 'active_record'
require 'logger'
require 'sqlite3'
require 'colorize'
require 'cli/ui'

# puts <<~HEREDOC
#   \e[31mThis text is red.\e[0m
#   \e[32mThis text is green.\e[0m
#   \e[33mThis text is yellow.\e[0m
#   \e[34mThis text is blue.\e[0m
# HEREDOC

require_relative 'setup'

# Define user modela
class User < ApplicationRecord
  # self.strict_loading_by_default = true

  has_many :comments
end

# Define post modela
class Post < ApplicationRecord
  # self.strict_loading_by_default = true
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments
end

# Define comment model
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :votes, class_name: 'CommentVote'
end

# Define comment vote model
class CommentVote < ApplicationRecord
  belongs_to :voter, class_name: 'User'
  belongs_to :comment
end

def seed_comments(count:)
  ActiveRecord::Base.logger = nil

  post_ids = Post.pluck(:id)
  user_ids = User.pluck(:id)
  (1..count).each do |i|
    post_id = post_ids.sample
    user_id = user_ids.sample
    comment = Comment.create(body: "Comment #{i}", post_id:, user_id:)
    Post.find(post_id).update(user_id:)
    CommentVote.create(comment_id: comment.id, voter_id: user_id)
  end
  ActiveRecord::Base.logger = Logger.new($stdout)
end

##### Everything above this line should carry forward
##### from page to page. Below is where changes are made
##### to follow along with the book.

seed_posts(count: 2)
seed_users(count: 2)
seed_comments(count: 10)

def print_posts(posts)
  posts.each do |post|
    puts
    puts "Post: #{post.title}"
    puts "Author: #{post.author.first_name}"
    puts "Comments: #{post.comments.map(&:body)}"
    puts "Comments count: #{post.comments.size}"
    puts "Commenters: #{post.comments.map { |comment| comment.user.first_name }}"
  end
end

def without_references(*args)
  banner = <<~BANNER
    Page 32, Extracting comments from posts using includes/where performs
    a LEFT OUTER JOIN between posts and comments.
  BANNER
  puts banner.yellow

  posts = Post.includes(:comments).where(comments: {body: "Comment 1"}).to_a
  print_posts(posts)
end

def with_references(*args)
  banner = <<~BANNER
    Page 32, Extracting comments from posts using includes/where performs
    a LEFT OUTER JOIN between posts and comments. In this case, the where
    clause is a string of SQL, so we need to use references to tell Rails
    to include the comments table in the query.
  BANNER
  puts banner.yellow

  posts = Post.includes(:comments).where("comments.body = ?", "Comment 2").references(:comments)
  print_posts(posts)
end

# TODO: Page 32 .includes with .references.
# Take a look at the SQL generated by .includes with .references.

CLI::UI::Prompt.instructions_color = CLI::UI::Color::GRAY
CLI::UI::Prompt.ask('What language/framework do you use?') do |handler|
  handler.option('includes without references', &method(:without_references))
  handler.option('includes with references', &method(:with_references))
end
